import { vars } from 'nativewind';
import { getColor } from './colors';

// Config using the wrapper
export const config = {
  light: vars({
    '--color-primary-0': getColor('primary', '0', 'light'),
    '--color-primary-50': getColor('primary', '50', 'light'),
    '--color-primary-100': getColor('primary', '100', 'light'),
    '--color-primary-200': getColor('primary', '200', 'light'),
    '--color-primary-300': getColor('primary', '300', 'light'),
    '--color-primary-400': getColor('primary', '400', 'light'),
    '--color-primary-500': getColor('primary', '500', 'light'),
    '--color-primary-600': getColor('primary', '600', 'light'),
    '--color-primary-700': getColor('primary', '700', 'light'),
    '--color-primary-800': getColor('primary', '800', 'light'),
    '--color-primary-900': getColor('primary', '900', 'light'),
    '--color-primary-950': getColor('primary', '950', 'light'),

    '--color-secondary-0': getColor('secondary', '0', 'light'),
    '--color-secondary-50': getColor('secondary', '50', 'light'),
    '--color-secondary-100': getColor('secondary', '100', 'light'),
    '--color-secondary-200': getColor('secondary', '200', 'light'),
    '--color-secondary-300': getColor('secondary', '300', 'light'),
    '--color-secondary-400': getColor('secondary', '400', 'light'),
    '--color-secondary-500': getColor('secondary', '500', 'light'),
    '--color-secondary-600': getColor('secondary', '600', 'light'),
    '--color-secondary-700': getColor('secondary', '700', 'light'),
    '--color-secondary-800': getColor('secondary', '800', 'light'),
    '--color-secondary-900': getColor('secondary', '900', 'light'),
    '--color-secondary-950': getColor('secondary', '950', 'light'),

    '--color-tertiary-0': getColor('tertiary', '0', 'light'),
    '--color-tertiary-50': getColor('tertiary', '50', 'light'),
    '--color-tertiary-100': getColor('tertiary', '100', 'light'),
    '--color-tertiary-200': getColor('tertiary', '200', 'light'),
    '--color-tertiary-300': getColor('tertiary', '300', 'light'),
    '--color-tertiary-400': getColor('tertiary', '400', 'light'),
    '--color-tertiary-500': getColor('tertiary', '500', 'light'),
    '--color-tertiary-600': getColor('tertiary', '600', 'light'),
    '--color-tertiary-700': getColor('tertiary', '700', 'light'),
    '--color-tertiary-800': getColor('tertiary', '800', 'light'),
    '--color-tertiary-900': getColor('tertiary', '900', 'light'),
    '--color-tertiary-950': getColor('tertiary', '950', 'light'),

    '--color-quaternary-0': getColor('quaternary', '0', 'light'),
    '--color-quaternary-50': getColor('quaternary', '50', 'light'),
    '--color-quaternary-100': getColor('quaternary', '100', 'light'),
    '--color-quaternary-200': getColor('quaternary', '200', 'light'),
    '--color-quaternary-300': getColor('quaternary', '300', 'light'),
    '--color-quaternary-400': getColor('quaternary', '400', 'light'),
    '--color-quaternary-500': getColor('quaternary', '500', 'light'),
    '--color-quaternary-600': getColor('quaternary', '600', 'light'),
    '--color-quaternary-700': getColor('quaternary', '700', 'light'),
    '--color-quaternary-800': getColor('quaternary', '800', 'light'),
    '--color-quaternary-900': getColor('quaternary', '900', 'light'),
    '--color-quaternary-950': getColor('quaternary', '950', 'light'),

    '--color-error-0': getColor('error', '0', 'light'),
    '--color-error-50': getColor('error', '50', 'light'),
    '--color-error-100': getColor('error', '100', 'light'),
    '--color-error-200': getColor('error', '200', 'light'),
    '--color-error-300': getColor('error', '300', 'light'),
    '--color-error-400': getColor('error', '400', 'light'),
    '--color-error-500': getColor('error', '500', 'light'),
    '--color-error-600': getColor('error', '600', 'light'),
    '--color-error-700': getColor('error', '700', 'light'),
    '--color-error-800': getColor('error', '800', 'light'),
    '--color-error-900': getColor('error', '900', 'light'),
    '--color-error-950': getColor('error', '950', 'light'),

    '--color-success-0': getColor('success', '0', 'light'),
    '--color-success-50': getColor('success', '50', 'light'),
    '--color-success-100': getColor('success', '100', 'light'),
    '--color-success-200': getColor('success', '200', 'light'),
    '--color-success-300': getColor('success', '300', 'light'),
    '--color-success-400': getColor('success', '400', 'light'),
    '--color-success-500': getColor('success', '500', 'light'),
    '--color-success-600': getColor('success', '600', 'light'),
    '--color-success-700': getColor('success', '700', 'light'),
    '--color-success-800': getColor('success', '800', 'light'),
    '--color-success-900': getColor('success', '900', 'light'),
    '--color-success-950': getColor('success', '950', 'light'),

    '--color-warning-0': getColor('warning', '0', 'light'),
    '--color-warning-50': getColor('warning', '50', 'light'),
    '--color-warning-100': getColor('warning', '100', 'light'),
    '--color-warning-200': getColor('warning', '200', 'light'),
    '--color-warning-300': getColor('warning', '300', 'light'),
    '--color-warning-400': getColor('warning', '400', 'light'),
    '--color-warning-500': getColor('warning', '500', 'light'),
    '--color-warning-600': getColor('warning', '600', 'light'),
    '--color-warning-700': getColor('warning', '700', 'light'),
    '--color-warning-800': getColor('warning', '800', 'light'),
    '--color-warning-900': getColor('warning', '900', 'light'),
    '--color-warning-950': getColor('warning', '950', 'light'),

    '--color-info-0': getColor('info', '0', 'light'),
    '--color-info-50': getColor('info', '50', 'light'),
    '--color-info-100': getColor('info', '100', 'light'),
    '--color-info-200': getColor('info', '200', 'light'),
    '--color-info-300': getColor('info', '300', 'light'),
    '--color-info-400': getColor('info', '400', 'light'),
    '--color-info-500': getColor('info', '500', 'light'),
    '--color-info-600': getColor('info', '600', 'light'),
    '--color-info-700': getColor('info', '700', 'light'),
    '--color-info-800': getColor('info', '800', 'light'),
    '--color-info-900': getColor('info', '900', 'light'),
    '--color-info-950': getColor('info', '950', 'light'),

    '--color-typography-0': getColor('typography', '0', 'light'),
    '--color-typography-50': getColor('typography', '50', 'light'),
    '--color-typography-100': getColor('typography', '100', 'light'),
    '--color-typography-200': getColor('typography', '200', 'light'),
    '--color-typography-300': getColor('typography', '300', 'light'),
    '--color-typography-400': getColor('typography', '400', 'light'),
    '--color-typography-500': getColor('typography', '500', 'light'),
    '--color-typography-600': getColor('typography', '600', 'light'),
    '--color-typography-700': getColor('typography', '700', 'light'),
    '--color-typography-800': getColor('typography', '800', 'light'),
    '--color-typography-900': getColor('typography', '900', 'light'),
    '--color-typography-950': getColor('typography', '950', 'light'),

    '--color-outline-0': getColor('outline', '0', 'light'),
    '--color-outline-50': getColor('outline', '50', 'light'),
    '--color-outline-100': getColor('outline', '100', 'light'),
    '--color-outline-200': getColor('outline', '200', 'light'),
    '--color-outline-300': getColor('outline', '300', 'light'),
    '--color-outline-400': getColor('outline', '400', 'light'),
    '--color-outline-500': getColor('outline', '500', 'light'),
    '--color-outline-600': getColor('outline', '600', 'light'),
    '--color-outline-700': getColor('outline', '700', 'light'),
    '--color-outline-800': getColor('outline', '800', 'light'),
    '--color-outline-900': getColor('outline', '900', 'light'),
    '--color-outline-950': getColor('outline', '950', 'light'),

    '--color-background-0': getColor('background', '0', 'light'),
    '--color-background-50': getColor('background', '50', 'light'),
    '--color-background-100': getColor('background', '100', 'light'),
    '--color-background-200': getColor('background', '200', 'light'),
    '--color-background-300': getColor('background', '300', 'light'),
    '--color-background-400': getColor('background', '400', 'light'),
    '--color-background-500': getColor('background', '500', 'light'),
    '--color-background-600': getColor('background', '600', 'light'),
    '--color-background-700': getColor('background', '700', 'light'),
    '--color-background-800': getColor('background', '800', 'light'),
    '--color-background-900': getColor('background', '900', 'light'),
    '--color-background-950': getColor('background', '950', 'light'),

    '--color-background-error': getColor('special', 'backgroundError', 'light'),
    '--color-background-warning': getColor('special', 'backgroundWarning', 'light'),
    '--color-background-success': getColor('special', 'backgroundSuccess', 'light'),
    '--color-background-muted': getColor('special', 'backgroundMuted', 'light'),
    '--color-background-info': getColor('special', 'backgroundInfo', 'light'),
    '--color-indicator-primary': getColor('special', 'indicatorPrimary', 'light'),
    '--color-indicator-info': getColor('special', 'indicatorInfo', 'light'),
    '--color-indicator-error': getColor('special', 'indicatorError', 'light'),
  }),
  dark: vars({
    '--color-primary-0': getColor('primary', '0', 'dark'),
    '--color-primary-50': getColor('primary', '50', 'dark'),
    '--color-primary-100': getColor('primary', '100', 'dark'),
    '--color-primary-200': getColor('primary', '200', 'dark'),
    '--color-primary-300': getColor('primary', '300', 'dark'),
    '--color-primary-400': getColor('primary', '400', 'dark'),
    '--color-primary-500': getColor('primary', '500', 'dark'),
    '--color-primary-600': getColor('primary', '600', 'dark'),
    '--color-primary-700': getColor('primary', '700', 'dark'),
    '--color-primary-800': getColor('primary', '800', 'dark'),
    '--color-primary-900': getColor('primary', '900', 'dark'),
    '--color-primary-950': getColor('primary', '950', 'dark'),

    '--color-secondary-0': getColor('secondary', '0', 'dark'),
    '--color-secondary-50': getColor('secondary', '50', 'dark'),
    '--color-secondary-100': getColor('secondary', '100', 'dark'),
    '--color-secondary-200': getColor('secondary', '200', 'dark'),
    '--color-secondary-300': getColor('secondary', '300', 'dark'),
    '--color-secondary-400': getColor('secondary', '400', 'dark'),
    '--color-secondary-500': getColor('secondary', '500', 'dark'),
    '--color-secondary-600': getColor('secondary', '600', 'dark'),
    '--color-secondary-700': getColor('secondary', '700', 'dark'),
    '--color-secondary-800': getColor('secondary', '800', 'dark'),
    '--color-secondary-900': getColor('secondary', '900', 'dark'),
    '--color-secondary-950': getColor('secondary', '950', 'dark'),

    '--color-tertiary-0': getColor('tertiary', '0', 'dark'),
    '--color-tertiary-50': getColor('tertiary', '50', 'dark'),
    '--color-tertiary-100': getColor('tertiary', '100', 'dark'),
    '--color-tertiary-200': getColor('tertiary', '200', 'dark'),
    '--color-tertiary-300': getColor('tertiary', '300', 'dark'),
    '--color-tertiary-400': getColor('tertiary', '400', 'dark'),
    '--color-tertiary-500': getColor('tertiary', '500', 'dark'),
    '--color-tertiary-600': getColor('tertiary', '600', 'dark'),
    '--color-tertiary-700': getColor('tertiary', '700', 'dark'),
    '--color-tertiary-800': getColor('tertiary', '800', 'dark'),
    '--color-tertiary-900': getColor('tertiary', '900', 'dark'),
    '--color-tertiary-950': getColor('tertiary', '950', 'dark'),

    '--color-quaternary-0': getColor('quaternary', '0', 'dark'),
    '--color-quaternary-50': getColor('quaternary', '50', 'dark'),
    '--color-quaternary-100': getColor('quaternary', '100', 'dark'),
    '--color-quaternary-200': getColor('quaternary', '200', 'dark'),
    '--color-quaternary-300': getColor('quaternary', '300', 'dark'),
    '--color-quaternary-400': getColor('quaternary', '400', 'dark'),
    '--color-quaternary-500': getColor('quaternary', '500', 'dark'),
    '--color-quaternary-600': getColor('quaternary', '600', 'dark'),
    '--color-quaternary-700': getColor('quaternary', '700', 'dark'),
    '--color-quaternary-800': getColor('quaternary', '800', 'dark'),
    '--color-quaternary-900': getColor('quaternary', '900', 'dark'),
    '--color-quaternary-950': getColor('quaternary', '950', 'dark'),

    '--color-error-0': getColor('error', '0', 'dark'),
    '--color-error-50': getColor('error', '50', 'dark'),
    '--color-error-100': getColor('error', '100', 'dark'),
    '--color-error-200': getColor('error', '200', 'dark'),
    '--color-error-300': getColor('error', '300', 'dark'),
    '--color-error-400': getColor('error', '400', 'dark'),
    '--color-error-500': getColor('error', '500', 'dark'),
    '--color-error-600': getColor('error', '600', 'dark'),
    '--color-error-700': getColor('error', '700', 'dark'),
    '--color-error-800': getColor('error', '800', 'dark'),
    '--color-error-900': getColor('error', '900', 'dark'),
    '--color-error-950': getColor('error', '950', 'dark'),

    '--color-success-0': getColor('success', '0', 'dark'),
    '--color-success-50': getColor('success', '50', 'dark'),
    '--color-success-100': getColor('success', '100', 'dark'),
    '--color-success-200': getColor('success', '200', 'dark'),
    '--color-success-300': getColor('success', '300', 'dark'),
    '--color-success-400': getColor('success', '400', 'dark'),
    '--color-success-500': getColor('success', '500', 'dark'),
    '--color-success-600': getColor('success', '600', 'dark'),
    '--color-success-700': getColor('success', '700', 'dark'),
    '--color-success-800': getColor('success', '800', 'dark'),
    '--color-success-900': getColor('success', '900', 'dark'),
    '--color-success-950': getColor('success', '950', 'dark'),

    '--color-warning-0': getColor('warning', '0', 'dark'),
    '--color-warning-50': getColor('warning', '50', 'dark'),
    '--color-warning-100': getColor('warning', '100', 'dark'),
    '--color-warning-200': getColor('warning', '200', 'dark'),
    '--color-warning-300': getColor('warning', '300', 'dark'),
    '--color-warning-400': getColor('warning', '400', 'dark'),
    '--color-warning-500': getColor('warning', '500', 'dark'),
    '--color-warning-600': getColor('warning', '600', 'dark'),
    '--color-warning-700': getColor('warning', '700', 'dark'),
    '--color-warning-800': getColor('warning', '800', 'dark'),
    '--color-warning-900': getColor('warning', '900', 'dark'),
    '--color-warning-950': getColor('warning', '950', 'dark'),

    '--color-info-0': getColor('info', '0', 'dark'),
    '--color-info-50': getColor('info', '50', 'dark'),
    '--color-info-100': getColor('info', '100', 'dark'),
    '--color-info-200': getColor('info', '200', 'dark'),
    '--color-info-300': getColor('info', '300', 'dark'),
    '--color-info-400': getColor('info', '400', 'dark'),
    '--color-info-500': getColor('info', '500', 'dark'),
    '--color-info-600': getColor('info', '600', 'dark'),
    '--color-info-700': getColor('info', '700', 'dark'),
    '--color-info-800': getColor('info', '800', 'dark'),
    '--color-info-900': getColor('info', '900', 'dark'),
    '--color-info-950': getColor('info', '950', 'dark'),

    '--color-typography-0': getColor('typography', '0', 'dark'),
    '--color-typography-50': getColor('typography', '50', 'dark'),
    '--color-typography-100': getColor('typography', '100', 'dark'),
    '--color-typography-200': getColor('typography', '200', 'dark'),
    '--color-typography-300': getColor('typography', '300', 'dark'),
    '--color-typography-400': getColor('typography', '400', 'dark'),
    '--color-typography-500': getColor('typography', '500', 'dark'),
    '--color-typography-600': getColor('typography', '600', 'dark'),
    '--color-typography-700': getColor('typography', '700', 'dark'),
    '--color-typography-800': getColor('typography', '800', 'dark'),
    '--color-typography-900': getColor('typography', '900', 'dark'),
    '--color-typography-950': getColor('typography', '950', 'dark'),

    '--color-outline-0': getColor('outline', '0', 'dark'),
    '--color-outline-50': getColor('outline', '50', 'dark'),
    '--color-outline-100': getColor('outline', '100', 'dark'),
    '--color-outline-200': getColor('outline', '200', 'dark'),
    '--color-outline-300': getColor('outline', '300', 'dark'),
    '--color-outline-400': getColor('outline', '400', 'dark'),
    '--color-outline-500': getColor('outline', '500', 'dark'),
    '--color-outline-600': getColor('outline', '600', 'dark'),
    '--color-outline-700': getColor('outline', '700', 'dark'),
    '--color-outline-800': getColor('outline', '800', 'dark'),
    '--color-outline-900': getColor('outline', '900', 'dark'),
    '--color-outline-950': getColor('outline', '950', 'dark'),

    '--color-background-0': getColor('background', '0', 'dark'),
    '--color-background-50': getColor('background', '50', 'dark'),
    '--color-background-100': getColor('background', '100', 'dark'),
    '--color-background-200': getColor('background', '200', 'dark'),
    '--color-background-300': getColor('background', '300', 'dark'),
    '--color-background-400': getColor('background', '400', 'dark'),
    '--color-background-500': getColor('background', '500', 'dark'),
    '--color-background-600': getColor('background', '600', 'dark'),
    '--color-background-700': getColor('background', '700', 'dark'),
    '--color-background-800': getColor('background', '800', 'dark'),
    '--color-background-900': getColor('background', '900', 'dark'),
    '--color-background-950': getColor('background', '950', 'dark'),

    '--color-background-error': getColor('special', 'backgroundError', 'dark'),
    '--color-background-warning': getColor('special', 'backgroundWarning', 'dark'),
    '--color-background-success': getColor('special', 'backgroundSuccess', 'dark'),
    '--color-background-muted': getColor('special', 'backgroundMuted', 'dark'),
    '--color-background-info': getColor('special', 'backgroundInfo', 'dark'),
    '--color-indicator-primary': getColor('special', 'indicatorPrimary', 'dark'),
    '--color-indicator-info': getColor('special', 'indicatorInfo', 'dark'),
    '--color-indicator-error': getColor('special', 'indicatorError', 'dark'),
  }),
};