import { mapDbGenderToGender, mapGenderToDbGender } from "@/mappers/gender";
import { Tables, TablesInsert } from "@/supabase/types";
import { Child, ChildCreate } from "@/types/models/children";

export const mapDbChildToChild = (child: Tables<"children">): Child => {
  return {
    id: child.id,
    firstName: child.first_name,
    lastName: child.last_name,
    birthDate: child.birth_date ? new Date(child.birth_date) : null,
    gender: mapDbGenderToGender(child.gender),
    accessCode: child.access_code,
    createdAt: new Date(child.created_at)
  };
}

export const mapChildCreateToDbChild = (child: ChildCreate): TablesInsert<"children"> => {
  return {
    first_name: child.firstName,
    last_name: child.lastName,
    birth_date: child.birthDate,
    gender: mapGenderToDbGender(child.gender),
    access_code: "",  // will be generated by the database
  }
}