import { mapDbGenderToGender, mapGenderToDbGender } from "@/mappers/gender";
import { Tables, TablesInsert, TablesUpdate } from "@/supabase/types";
import { PickerItemWithoutNull } from "@/types/base";
import { Child, ChildCreate, ChildUpdate } from "@/types/models/children";
import { formatISOLocalToHumanReadable } from "@/utils/dates";

const BASE_PICKER_DATA = [{ id: null, showedText: '-' }];

export const mapDbChildToChild = (child: Tables<"children">): Child => {
  return {
    id: child.id,
    firstName: child.first_name,
    lastName: child.last_name,
    birthDate: child.birth_date ? new Date(child.birth_date) : null,
    gender: mapDbGenderToGender(child.gender),
    accessCode: child.access_code,
    createdAt: new Date(child.created_at)
  };
}

export const mapChildCreateToDbChild = (child: ChildCreate): TablesInsert<"children"> => {
  return {
    first_name: child.firstName,
    last_name: child.lastName,
    birth_date: child.birthDate,
    gender: mapGenderToDbGender(child.gender),
    access_code: "",  // will be generated by the database
  }
}

export const mapChildUpdateToDbChild = (child: ChildUpdate): TablesUpdate<"children"> => {
  return {
    first_name: child.firstName,
    last_name: child.lastName,
    birth_date: child.birthDate,
    gender: mapGenderToDbGender(child.gender!),
  }
}

const mapChildToPickerItem = (child: Child): PickerItemWithoutNull => {
  return {
    id: child.id,
    showedText: `${child.lastName}, ${child.firstName}`,
    helperText: formatISOLocalToHumanReadable(child.birthDate),
  };
}

export const mapManyChilrenToPickerItems = (children: Child[] | undefined): PickerItemWithoutNull[] => {
  if (children === undefined || children.length === 0) {
    return [];
  }

  return [
    ...children.map((child) => mapChildToPickerItem(child))
  ];
}